AnimalShelterApp/Models/Animal.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelterApp.Models
{
    public class Animal
    {
        public int Id {get; set;}
        public string Name {get; set;}
        public DateTime? start_date {get; set;}
        public string Type {get; set;}
        public string Breed {get; set;}
    }
}

AnimalShelterApp/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelterApp.Models
{
    public class AnimalShelterContext : DbContext
    {
        public DbSet<Animal> Animals { get; set; }

        public AnimalShelterContext(DbContextOptions options) : base(options) { }
    }
}

AnimalShelterApp/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelterApp.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelterApp.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly AnimalShelterContext _db;

        public AnimalsController(AnimalShelterContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Animal> model = _db.Animals.ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Animal animal)
        {
            _db.Animals.Add(animal);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Display(int id)
        {
            Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.Id == id);
            return View(thisAnimal);
        }


    }
}

AnimalShelterApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelterApp.Models;

namespace AnimalShelterApp.Controllers
{
  public class HomeController : Controller
  {
    [Route("/")]
    public ActionResult Index() {
      return View();
    }
  }
}

AnimalShelterApp/Views/Animals/Create.cshtml
@{
    Layout = "_Layout";
}

@model AnimalShelterApp.Models.Animal

<body style="text-align: center; padding-top: 40px;">
<h4 style="text-align: center; padding-top: 40px;">Add a new animal</h4>


@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <label for="start_date">start_date</label>
    <input type="datetime-local" name="start_date" id="start_date">
    @Html.LabelFor(model => model.Type)
    @Html.TextBoxFor(model => model.Type)
    @Html.LabelFor(model => model.Breed)
    @Html.TextBoxFor(model => model.Breed)
    <input type="submit" value="Add new animal" />
}
<p style="text-align: center; padding-top: 40px;">@Html.ActionLink("Show all animals", "Index")</p>
    
</body>

AnimalShelterApp/Views/Animals/Display.cshtml
@{
    Layout = "_Layout";
}

@using AnimalShelterApp.Models;

<div class="container">
    <div class="text-center">
        <h1 class="pt-3">Animal Details</h1>
        <div class="my-4">
            <ul class="list-group w-25 m-auto">
                <li class="list-group-item pt-2 link-text"
                    style="text-align: center; padding-top: 40px; list-style: none;">
                    Name: @Model.Name
                </li>
                <li class="list-group-item pt-2 link-text"
                    style="text-align: center; padding-top: 40px; list-style: none;">
                    Admittance Date: @Model.start_date
                </li>
                <li class="list-group-item pt-2 link-text"
                    style="text-align: center; padding-top: 40px; list-style: none;">
                    Type: @Model.Type
                </li>
                <li class="list-group-item pt-2 link-text"
                    style="text-align: center; padding-top: 40px; list-style: none;">
                    Breed: @Model.Breed
                </li>
            </ul>
        </div>
    </div>
</div>
<p style="text-align: center; padding-top: 40px;"><a href="/animals">Back Home!</a></p>

AnimalShelterApp/Views/Animals/Index.cshtml
@{
    Layout = "_Layout";
}

@using AnimalShelterApp.Models;

<div class="container">
  <div class="text-center">
        <h1 class="pt-3">Animals</h1>

        @if (@Model.Count == 0)
        {
            <h3 class="pt-3">No animals have been added yet!</h3>
        }
        <div class="my-4">
            <ul class="list-group w-25 m-auto">
                @foreach (Animal animal in Model)
                {
                    <li class="list-group-item pt-2 link-text">@Html.ActionLink($"{animal.Name}", "Display", new { id = animal.Id })</li>
                }
            </ul>
        </div>

        <p class="link-text">@Html.ActionLink("Add new item!", "Create")</p>
        <p class="link-text">@Html.ActionLink("Back home!", "Index", "Home")</p>
  </div>
</div>

AnimalShelterApp/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<div class="container">
  <div class="text-center">
    <h1 class="pt-3">Welcome to the Animal Shelter!</h1>
    <h3 class="pt-3">@Html.ActionLink("See all animals", "Index", "Animals")</h3>
  </div>
</div>

AnimalShelterApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Animal Shelter!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/styles.css">
</head>

<body>
    @RenderBody()
</body>

</html>